<?php

use Illuminate\Database\Seeder;

class TanimUzmanlikAlaniSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $query = [
            ['alanadi' => 'İç Hastalıkları','ustid' => 0,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Alerji Hastalıkları','ustid' => 1,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Endokrinoloji ve Metabolizma Hastalıkları','ustid' => 1,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Gastroenteroloji','ustid' => 1,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Nefroloji','ustid' => 1,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Romatoloji','ustid' => 1,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'İş ve Meslek Hastalıkları','ustid' => 1,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'İmmünoloji','ustid' => 1,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Hematoloji','ustid' => 1,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Geriatri','ustid' => 1,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Tıbbi Onkoloji','ustid' => 1,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Yoğun Bakım','ustid' => 1,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Kardiyoloji','ustid' => 0,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Göğüs Hastalıkları','ustid' => 0,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Alerjik Göğüs Hastalıkları','ustid' => 14,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Enfeksiyon Hastalıkları','ustid' => 0,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Nöroloji','ustid' => 0,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Psikiyatri','ustid' => 0,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Çocuk Sağlığı ve Hastalıkları','ustid' => 0,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Çocuk Kardiyolojisi','ustid' => 19,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Çocuk Metabolizma Hastalıkları','ustid' => 19,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Çocuk Endokrinolojisi','ustid' => 19,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Çocuk Hematolojisi','ustid' => 19,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Çocuk Nefrolojisi','ustid' => 19,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Çocuk Nörolojisi','ustid' => 19,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Çocuk Alerjisi','ustid' => 19,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Çocuk Onkolojisi','ustid' => 19,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Çocuk Gastroenteroloji, Hepatoloji ve Beslenme','ustid' => 19,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Çocuk Enfeksiyon Hastalıkları','ustid' => 19,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Neonatoloji','ustid' => 19,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Genetik','ustid' => 19,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Çocuk Göğüs Hastalıkları','ustid' => 19,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Çocuk İmmünolojisi','ustid' => 19,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Çocuk Yoğun Bakım','ustid' => 19,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Çocuk Psikiyatrisi','ustid' => 0,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Dermatoloji','ustid' => 0,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Fiziksel Tıp ve Rehabilitasyon','ustid' => 0,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Romatoloji 2','ustid' => 37,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Genel Cerrahi','ustid' => 0,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Gastroentroloji Cerrahisi','ustid' => 39,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Çocuk Cerrahisi','ustid' => 0,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Çocuk Ürolojisi 2','ustid' => 41,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Göğüs Cerrahisi','ustid' => 0,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Kalp ve Damar Cerrahisi','ustid' => 0,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Çocuk Kalp ve Damar Cerrahisi','ustid' => 44,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Beyin ve Sinir Cerrahisi','ustid' => 0,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Plastik, Rekonstrüktif ve Estetik Cerrahi','ustid' => 0,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Plastik El Cerrahisi','ustid' => 48,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Ortopedi ve Travmatoloji','ustid' => 0,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Ortopedi El Cerrahisi','ustid' => 49,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Üroloji','ustid' => 0,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Çocuk Ürolojisi','ustid' => 51,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Androloji','ustid' => 51,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Kulak-Burun-Boğaz Hastalıkları','ustid' => 0,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Göz Hastalıkları','ustid' => 0,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Kadın Hastalıkları ve Doğum','ustid' => 0,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Üreme Endokrinolojisi ve İnfertilite','ustid' => 56,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Perinatoloji','ustid' => 56,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Anesteziyoloji ve Reanimasyon','ustid' => 0,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Algoloji','ustid' => 59,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Radyasyon Onkolojisi','ustid' => 0,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Radyoloji','ustid' => 0,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Nöroradyoloji','ustid' => 62,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Girişimsel Radyoloji','ustid' => 62,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Pediyatrik Radyoloji','ustid' => 62,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Nükleer Tıp','ustid' => 0,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Tıbbi Patoloji','ustid' => 0,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Sitopatoloji','ustid' => 67,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Dermatopatoloji','ustid' => 67,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Nöropatoloji','ustid' => 67,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Tıbbi Genetik','ustid' => 0,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Klinik Sitogenetik','ustid' => 71,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Klinik Moleküler Genetik','ustid' => 71,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Klinik Genetik','ustid' => 71,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Tıbbi Biyokimya','ustid' => 0,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Tıbbi Mikrobiyoloji','ustid' => 0,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Tıbbi Parazitoloji','ustid' => 76,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Viroloji','ustid' => 76,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'İmmünoloji 2','ustid' => 76,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Mikoloji','ustid' => 76,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Tıbbi Farmakoloji','ustid' => 0,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Toksikoloji','ustid' => 81,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Spor Hekimliği','ustid' => 0,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Askeri Sahra Hekimliği','ustid' => 0,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Hava ve Uzay Hekimliği','ustid' => 0,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Sualtı Hekimliği ve Hiperbarik Tıp','ustid' => 0,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Acil Tıp','ustid' => 0,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Adli Tıp','ustid' => 0,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Halk Sağlığı','ustid' => 0,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Epidemiyoloji','ustid' => 89,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Çevre Sağlığı','ustid' => 89,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'İşyeri Hekimliği','ustid' => 89,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Okul Hekimliği','ustid' => 89,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Fizyoloji','ustid' => 0,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Aile Hekimliği','ustid' => 0,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Anatomi','ustid' => 0,'dilid'=>'tr','durumu'=>1],
            ['alanadi' => 'Embriyoloji ve Histoloji','ustid' => 0,'dilid'=>'tr','durumu'=>1],
        ];

        foreach($query as $d){
            \App\Models\Panel\Tanim\TanimUzmanlikAlani::create($d);        
        }
    }
}
